import {clamp,type EncounterMetrics,type PlayerPerformanceProfile} from "./adaptive";

export type CombatStyle="aggressive"|"balanced"|"strategic"|"cautious";
export type AdaptivePacingRole="warmup"|"standard"|"pressure"|"recovery"|"experiment"|"challenge"|"elite"|"reward"|"pre_boss"|"boss";

export interface AdaptivePlayerProfile{
 schemaVersion:1;overallSkill:number;aimSkill:number;movementSkill:number;survivalSkill:number;reactionSkill:number;tacticalSkill:number;resourceSkill:number;reinforcementSkill:number;
 aggressionPreference:number;defensivePreference:number;preferredCombatDistance:number;explorationPreference:number;encounterLengthPreference:number;frustrationRisk:number;boredomRisk:number;
 confidence:{overall:number;aim:number;movement:number;survival:number;tactics:number;resources:number;reinforcements:number;preferences:number};recentRoomCount:number;lastUpdatedAt:string;
}
export interface RepeatedHabit{habitId:string;confidence:number;evidenceCount:number;firstObservedRoom:number;lastObservedRoom:number}
export interface PlayerHabitProfile{dominantWeaponId?:string;dominantAbilityId?:string;averageCombatDistance:number;rushFrequency:number;retreatFrequency:number;stationaryCombatRatio:number;preferredMovementDirection:"clockwise"|"counterclockwise"|"mixed";coverUsageRate:number;flankAvoidanceRate:number;firstTargetRolePreference?:string;supportEnemyPriorityRate:number;nearestEnemyTargetRate:number;healEarlyRate:number;healLateRate:number;reinforcementSaveRate:number;reinforcementPanicUseRate:number;repeatedHabits:RepeatedHabit[]}
export interface PlayerPreferenceProfile{preferredDifficulty:number;preferredRoomDuration:number;preferredEnemyDensity:number;preferredTacticalComplexity:number;preferredPacingSpeed:number;preferredMapStyleIds:string[];dislikedEncounterTags:string[];confidence:number;adaptationStrength:number}
export interface PredictionCalibration{completionTimeFactor:number;damageFactor:number;killRateFactor:number;samples:number;byTemplate:Record<string,{completion:number;damage:number;killRate:number;samples:number}>}
export interface AdaptationExperiment{id:string;variableChanged:string;baselineValue:string|number;testValue:string|number;expectedEffect:string;startedAtRoom:number;completed:boolean}
export interface BossAttemptAnalysis{attempts:number;phaseReached:number;dominantDamageSource:string;dodgeSuccess:number;campingRatio:number;reinforcementUsage:number;lastDeathRoom:number;telegraphMultiplier:number;patternOrderOffset:number}
export interface AdaptiveMemory{schemaVersion:1;player:AdaptivePlayerProfile;habits:PlayerHabitProfile;preferences:PlayerPreferenceProfile;calibration:PredictionCalibration;pacingHistory:AdaptivePacingRole[];activeExperiment:AdaptationExperiment|null;boss:BossAttemptAnalysis;lastProcessedMetricKey:string;updatedAt:string}
export interface EnemyBehaviorProfile{id:string;aggression:number;preferredDistance:number;flankTendency:number;retreatThreshold:number;coverUsage:number;groupCoordination:number;reactionTimeMultiplier:number;attackFrequencyMultiplier:number;targetSwitchingRate:number;hazardAvoidance:number;difficultyCost:number;compatibleEnemyRoles:string[]}
export interface RoomModule{id:string;type:"entrance"|"arena"|"corridor"|"cover-pattern"|"flank-route"|"hazard-zone"|"objective-zone"|"pickup-zone"|"reinforcement-zone"|"exit";compatibleModuleIds:string[];incompatibleModuleIds:string[];difficultyCost:number;tags:string[];navigationMetadataId:string;spawnZoneIds:string[]}
export interface RoomPerformancePrediction{predictedCompletionTimeSeconds:number;predictedKillRate:number;predictedDamageTakenRatio:number;predictedDeathProbability:number;predictedReinforcementUsageProbability:number;confidence:number}

export const ENEMY_BEHAVIOR_PROFILES:EnemyBehaviorProfile[]=[
 {id:"cautious",aggression:.82,preferredDistance:.68,flankTendency:.12,retreatThreshold:.42,coverUsage:.7,groupCoordination:.38,reactionTimeMultiplier:1.08,attackFrequencyMultiplier:.88,targetSwitchingRate:.25,hazardAvoidance:.7,difficultyCost:1,compatibleEnemyRoles:["ranged","support","mixed"]},
 {id:"balanced",aggression:1,preferredDistance:.5,flankTendency:.28,retreatThreshold:.25,coverUsage:.45,groupCoordination:.5,reactionTimeMultiplier:1,attackFrequencyMultiplier:1,targetSwitchingRate:.4,hazardAvoidance:.55,difficultyCost:2,compatibleEnemyRoles:["melee","ranged","support","mixed","boss"]},
 {id:"aggressive",aggression:1.08,preferredDistance:.28,flankTendency:.3,retreatThreshold:.12,coverUsage:.2,groupCoordination:.45,reactionTimeMultiplier:.96,attackFrequencyMultiplier:1.06,targetSwitchingRate:.48,hazardAvoidance:.4,difficultyCost:3,compatibleEnemyRoles:["melee","mixed"]},
 {id:"flanking",aggression:1.02,preferredDistance:.48,flankTendency:.62,retreatThreshold:.24,coverUsage:.42,groupCoordination:.58,reactionTimeMultiplier:1,attackFrequencyMultiplier:1,targetSwitchingRate:.56,hazardAvoidance:.58,difficultyCost:4,compatibleEnemyRoles:["melee","ranged","mixed"]},
 {id:"coordinated",aggression:1.03,preferredDistance:.52,flankTendency:.4,retreatThreshold:.25,coverUsage:.55,groupCoordination:.78,reactionTimeMultiplier:.98,attackFrequencyMultiplier:1.03,targetSwitchingRate:.5,hazardAvoidance:.66,difficultyCost:4,compatibleEnemyRoles:["ranged","support","mixed","boss"]},
 {id:"area-control",aggression:.96,preferredDistance:.58,flankTendency:.2,retreatThreshold:.3,coverUsage:.5,groupCoordination:.6,reactionTimeMultiplier:1.02,attackFrequencyMultiplier:1.02,targetSwitchingRate:.35,hazardAvoidance:.72,difficultyCost:4,compatibleEnemyRoles:["ranged","support","mixed","boss"]},
];
export const ROOM_MODULES:RoomModule[]=[
 {id:"entrance-south",type:"entrance",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:0,tags:["safe-entry"],navigationMetadataId:"nav-entry-south",spawnZoneIds:[]},
 {id:"arena-open",type:"arena",compatibleModuleIds:[],incompatibleModuleIds:["corridor-tight"],difficultyCost:1,tags:["open","clear-lanes"],navigationMetadataId:"nav-arena-open",spawnZoneIds:["north_west","north_mid","north_east"]},
 {id:"arena-cover",type:"arena",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:2,tags:["cover","balanced"],navigationMetadataId:"nav-arena-cover",spawnZoneIds:["north_west","north_east","east","west"]},
 {id:"corridor-lanes",type:"corridor",compatibleModuleIds:[],incompatibleModuleIds:["arena-open"],difficultyCost:2,tags:["lanes","long-range"],navigationMetadataId:"nav-corridor-lanes",spawnZoneIds:["north_mid","east","west"]},
 {id:"cover-readable",type:"cover-pattern",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:1,tags:["readable","recovery"],navigationMetadataId:"nav-cover-readable",spawnZoneIds:[]},
 {id:"flank-single",type:"flank-route",compatibleModuleIds:[],incompatibleModuleIds:["flank-none"],difficultyCost:2,tags:["flank"],navigationMetadataId:"nav-flank-single",spawnZoneIds:["east","west"]},
 {id:"flank-none",type:"flank-route",compatibleModuleIds:[],incompatibleModuleIds:["flank-single"],difficultyCost:0,tags:["readable"],navigationMetadataId:"nav-flank-none",spawnZoneIds:[]},
 {id:"hazard-controlled",type:"hazard-zone",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:2,tags:["hazard"],navigationMetadataId:"nav-hazard-controlled",spawnZoneIds:[]},
 {id:"pickup-standard",type:"pickup-zone",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:0,tags:["resources"],navigationMetadataId:"nav-pickup-standard",spawnZoneIds:[]},
 {id:"reinforcement-safe",type:"reinforcement-zone",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:0,tags:["support"],navigationMetadataId:"nav-reinforcement-safe",spawnZoneIds:[]},
 {id:"exit-south",type:"exit",compatibleModuleIds:[],incompatibleModuleIds:[],difficultyCost:0,tags:["exit"],navigationMetadataId:"nav-exit-south",spawnZoneIds:[]},
];
const behaviorById=new Map(ENEMY_BEHAVIOR_PROFILES.map(x=>[x.id,x])),moduleById=new Map(ROOM_MODULES.map(x=>[x.id,x]));
export const getEnemyBehaviorProfile=(id:string)=>behaviorById.get(id);
export const getRoomModule=(id:string)=>moduleById.get(id);
const mean=(values:number[],fallback=0)=>values.length?values.reduce((a,b)=>a+b,0)/values.length:fallback;
const ratio=(a:number,b:number)=>clamp(a/Math.max(1,b));
const habit=(id:string,values:boolean[],roomIds:number[]):RepeatedHabit|null=>{const count=values.filter(Boolean).length,confidence=clamp(count/Math.max(3,values.length)*.85+Math.min(values.length,8)/8*.15);return count>=3&&confidence>=.65?{habitId:id,confidence,evidenceCount:count,firstObservedRoom:roomIds[values.findIndex(Boolean)]||roomIds[0]||0,lastObservedRoom:roomIds[values.length-1-values.slice().reverse().findIndex(Boolean)]||roomIds.at(-1)||0}:null};
export const metricFingerprint=(metric:EncounterMetrics|undefined)=>metric?`${metric.room}:${Math.round(metric.durationMs)}:${metric.shotsFired}:${metric.deaths}:${metric.completed?1:0}`:"";

export function deriveAdaptivePlayerProfile(base:PlayerPerformanceProfile|null,samples:EncounterMetrics[]):AdaptivePlayerProfile{
 const recent=samples.slice(-8),rooms=recent.length,completed=mean(recent.map(x=>x.completed?1:0)),fast=mean(recent.map(x=>x.durationMs<60000?1:0)),deathRate=mean(recent.map(x=>clamp(x.deaths))),damage=mean(recent.map(x=>ratio(x.damageTaken,x.healthAtStart||120))),movement=base?.dimensions.movement??.5,reinforcementUse=mean(recent.map(x=>x.reinforcementUsed?1:0));
 const overall=base?.overallSkillScore??.5,confidence=base?.confidenceScore??0,preferenceConfidence=clamp(rooms/8*.75+.1);
 return{schemaVersion:1,overallSkill:overall,aimSkill:base?.dimensions.aim??.5,movementSkill:movement,survivalSkill:base?.dimensions.survival??.5,reactionSkill:base?.dimensions.reaction??.5,tacticalSkill:base?.dimensions.tactical??.5,resourceSkill:base?.dimensions.resource??.5,reinforcementSkill:clamp(reinforcementUse*.45+(base?.dimensions.survival??.5)*.55),aggressionPreference:clamp(fast*.55+movement*.45),defensivePreference:clamp((1-damage)*.55+(1-fast)*.45),preferredCombatDistance:clamp(mean(recent.map(x=>x.averageCombatDistanceRatio??.5),.5)),explorationPreference:clamp(mean(recent.map(x=>x.explorationRatio??movement),movement)),encounterLengthPreference:clamp(1-mean(recent.map(x=>clamp((x.durationMs-30000)/100000)),.5)),frustrationRisk:clamp(deathRate*.5+damage*.32+(1-completed)*.18),boredomRisk:clamp(completed*.35+fast*.4+(1-damage)*.25-.55),confidence:{overall:confidence,aim:clamp(confidence*ratio(recent.reduce((n,x)=>n+x.shotsFired,0),80)),movement:clamp(confidence*rooms/5),survival:clamp(confidence*rooms/4),tactics:clamp(confidence*rooms/6),resources:clamp(confidence*rooms/6),reinforcements:clamp(rooms/8*reinforcementUse),preferences:preferenceConfidence},recentRoomCount:rooms,lastUpdatedAt:new Date().toISOString()};
}
export function deriveHabitProfile(samples:EncounterMetrics[],previous?:PlayerHabitProfile):PlayerHabitProfile{
 const recent=samples.slice(-8),ids=recent.map(x=>x.room),stationary=recent.map(x=>x.stationaryCombatRatio??1-ratio(x.movementMs,x.durationMs)),rush=recent.map(x=>x.rushFrequency??(x.durationMs<60000&&ratio(x.movementMs,x.durationMs)>.3?1:0)),retreat=recent.map(x=>x.retreatFrequency??(x.damageTaken>45?1:0)),late=recent.map(x=>Boolean(x.reinforcementUsed&&ratio(x.healthAtEnd??0,x.healthAtStart||120)<.35)),habits=[habit("stationary-combat",stationary.map(x=>x>.58),ids),habit("rush-entry",rush.map(x=>x>.55),ids),habit("late-reinforcement",late,ids),habit("long-range",recent.map(x=>(x.averageCombatDistanceRatio??.5)>.68),ids)].filter((x):x is RepeatedHabit=>Boolean(x));
 return{dominantWeaponId:recent.at(-1)?.dominantWeaponId||previous?.dominantWeaponId,dominantAbilityId:recent.at(-1)?.dominantAbilityId||previous?.dominantAbilityId,averageCombatDistance:mean(recent.map(x=>x.averageCombatDistanceRatio??previous?.averageCombatDistance??.5),.5),rushFrequency:mean(rush),retreatFrequency:mean(retreat),stationaryCombatRatio:mean(stationary),preferredMovementDirection:previous?.preferredMovementDirection||"mixed",coverUsageRate:mean(recent.map(x=>x.coverUsageRate??.5),.5),flankAvoidanceRate:mean(recent.map(x=>x.flankAvoidanceRate??.5),.5),firstTargetRolePreference:previous?.firstTargetRolePreference,supportEnemyPriorityRate:mean(recent.map(x=>x.supportEnemyPriorityRate??.5),.5),nearestEnemyTargetRate:mean(recent.map(x=>x.nearestEnemyTargetRate??.5),.5),healEarlyRate:mean(recent.map(x=>x.healEarlyRate??0)),healLateRate:mean(recent.map(x=>x.healLateRate??0)),reinforcementSaveRate:1-mean(recent.map(x=>x.reinforcementUsed?1:0)),reinforcementPanicUseRate:mean(late.map(Boolean).map(x=>x?1:0)),repeatedHabits:[...(previous?.repeatedHabits||[]).filter(old=>!habits.some(x=>x.habitId===old.habitId)),...habits].slice(-8)};
}
export function defaultPreferenceProfile():PlayerPreferenceProfile{return{preferredDifficulty:.5,preferredRoomDuration:.5,preferredEnemyDensity:.5,preferredTacticalComplexity:.5,preferredPacingSpeed:.5,preferredMapStyleIds:[],dislikedEncounterTags:[],confidence:.25,adaptationStrength:.65}}
export function createAdaptiveMemory(base:PlayerPerformanceProfile|null=null,samples:EncounterMetrics[]=[]):AdaptiveMemory{return{schemaVersion:1,player:deriveAdaptivePlayerProfile(base,samples),habits:deriveHabitProfile(samples),preferences:defaultPreferenceProfile(),calibration:{completionTimeFactor:1,damageFactor:1,killRateFactor:1,samples:0,byTemplate:{}},pacingHistory:[],activeExperiment:null,boss:{attempts:0,phaseReached:0,dominantDamageSource:"unknown",dodgeSuccess:.5,campingRatio:0,reinforcementUsage:0,lastDeathRoom:0,telegraphMultiplier:1,patternOrderOffset:0},lastProcessedMetricKey:metricFingerprint(samples.at(-1)),updatedAt:new Date().toISOString()}}
export function updateAdaptiveMemory(previous:AdaptiveMemory|undefined,base:PlayerPerformanceProfile,samples:EncounterMetrics[]):AdaptiveMemory{const prior=previous||createAdaptiveMemory(base,samples);return{...prior,player:deriveAdaptivePlayerProfile(base,samples),habits:deriveHabitProfile(samples,prior.habits),lastProcessedMetricKey:metricFingerprint(samples.at(-1)),updatedAt:new Date().toISOString()}}
export function actionableHabit(profile:PlayerHabitProfile,id:string){const found=profile.repeatedHabits.find(x=>x.habitId===id);return found&&found.evidenceCount>=3&&found.confidence>=.65?found:null}
export function selectPacingRole(memory:AdaptiveMemory,room:number,boss:boolean):AdaptivePacingRole{if(boss)return"boss";if(room>6&&(room+1)%5===0)return"pre_boss";const p=memory.player,recent=memory.pacingHistory.slice(-3);if(p.frustrationRisk>.58)return"recovery";if(recent.at(-1)==="elite"||recent.at(-1)==="boss")return"reward";if(p.boredomRisk>.5)return p.confidence.overall>.55?"challenge":"experiment";if(p.overallSkill>.72&&p.confidence.overall>.55)return"pressure";return room<=6?"warmup":"standard"}
export function selectBehaviorProfile(memory:AdaptiveMemory,role:AdaptivePacingRole,seedValue:number):EnemyBehaviorProfile{const p=memory.player,h=memory.habits,actionable=h.repeatedHabits.filter(x=>x.evidenceCount>=3&&x.confidence>=.65),counterChance=Math.min(.35,mean(actionable.map(x=>x.confidence))*memory.preferences.adaptationStrength*.5),counter=seedValue<counterChance;if(role==="recovery")return behaviorById.get("cautious")!;if(role==="boss")return behaviorById.get(p.overallSkill>.7?"coordinated":"balanced")!;if(counter&&actionable.some(x=>x.habitId==="stationary-combat"))return behaviorById.get("area-control")!;if(counter&&actionable.some(x=>x.habitId==="rush-entry"))return behaviorById.get("cautious")!;if(p.movementSkill>.68&&p.confidence.movement>.5)return behaviorById.get("flanking")!;if(p.tacticalSkill>.66)return behaviorById.get("coordinated")!;return behaviorById.get(p.aggressionPreference>.7?"aggressive":"balanced")!}
export function selectRoomModuleIds(tags:string[],memory:AdaptiveMemory,role:AdaptivePacingRole,hazard:boolean):string[]{const p=memory.player,modules=["entrance-south"];if(tags.includes("lanes")||p.preferredCombatDistance>.65)modules.push("corridor-lanes");else modules.push(tags.includes("open")?"arena-open":"arena-cover");modules.push(p.movementSkill<.38||role==="recovery"?"cover-readable":"pickup-standard");modules.push(p.movementSkill<.42||p.survivalSkill<.4?"flank-none":"flank-single");if(hazard&&p.survivalSkill>.42)modules.push("hazard-controlled");modules.push("reinforcement-safe","exit-south");return [...new Set(modules)]}
export function validateRoomModules(ids:string[]):boolean{const modules=ids.map(id=>moduleById.get(id));if(modules.some(x=>!x))return false;const set=new Set(ids);return modules.every(module=>module!.incompatibleModuleIds.every(id=>!set.has(id)))}
export function predictRoomPerformance(memory:AdaptiveMemory,input:{difficultyScore:number;estimatedDurationSeconds:number;enemyPressure:number;hazardPressure:number;resourceAvailability:number;templateId:string}):RoomPerformancePrediction{const p=memory.player,c=memory.calibration,relative=clamp(input.difficultyScore/90-p.overallSkill+.5),template=c.byTemplate[input.templateId],timeCalibration=template?.completion??c.completionTimeFactor,damageCalibration=template?.damage??c.damageFactor,killCalibration=template?.killRate??c.killRateFactor;return{predictedCompletionTimeSeconds:clamp(input.estimatedDurationSeconds*(.72+relative*.62)*timeCalibration,20,150),predictedKillRate:clamp((1.04-relative*.42)*killCalibration,.2,1),predictedDamageTakenRatio:clamp((.08+relative*.5+input.hazardPressure*.08-input.resourceAvailability*.05)*damageCalibration,.05,.8),predictedDeathProbability:clamp(relative*.52+p.frustrationRisk*.25-p.survivalSkill*.2,0,.85),predictedReinforcementUsageProbability:clamp(relative*.45+(1-p.reinforcementSkill)*.3+input.enemyPressure*.1,0,.9),confidence:clamp((p.confidence.overall+p.confidence.survival+p.confidence.tactics)/3)}}
export function calibratePrediction(previous:PredictionCalibration,prediction:RoomPerformancePrediction,actual:{completionTimeSeconds:number;killRate:number;damageTakenRatio:number},templateId:string):PredictionCalibration{const rate=.15,ratioFactor=(actualValue:number,predicted:number)=>clamp(actualValue/Math.max(.05,predicted),.7,1.3),update=(old:number,value:number)=>old*(1-rate)+value*rate,prior=previous.byTemplate[templateId]||{completion:1,damage:1,killRate:1,samples:0},nextTemplate={completion:update(prior.completion,ratioFactor(actual.completionTimeSeconds,prediction.predictedCompletionTimeSeconds)),damage:update(prior.damage,ratioFactor(actual.damageTakenRatio,prediction.predictedDamageTakenRatio)),killRate:update(prior.killRate,ratioFactor(actual.killRate,prediction.predictedKillRate)),samples:prior.samples+1};return{completionTimeFactor:update(previous.completionTimeFactor,ratioFactor(actual.completionTimeSeconds,prediction.predictedCompletionTimeSeconds)),damageFactor:update(previous.damageFactor,ratioFactor(actual.damageTakenRatio,prediction.predictedDamageTakenRatio)),killRateFactor:update(previous.killRateFactor,ratioFactor(actual.killRate,prediction.predictedKillRate)),samples:previous.samples+1,byTemplate:{...previous.byTemplate,[templateId]:nextTemplate}}}
export function maybeStartExperiment(memory:AdaptiveMemory,room:number,seedValue:number):AdaptationExperiment|null{if(memory.activeExperiment||memory.player.frustrationRisk>.45||room%5===0||seedValue>.22||memory.player.confidence.overall<.45)return memory.activeExperiment;return{id:`experiment-${room}-cover`,variableChanged:"coverDensity",baselineValue:"standard",testValue:"readable",expectedEffect:"Measure whether clearer cover improves survival without lowering enemy count.",startedAtRoom:room,completed:false}}
export function updateBossAnalysis(previous:BossAttemptAnalysis,metric:EncounterMetrics,bossRoom:boolean):BossAttemptAnalysis{if(!bossRoom||metric.completed)return previous;const attempts=previous.attempts+1,camping=metric.stationaryCombatRatio??1-ratio(metric.movementMs,metric.durationMs);return{...previous,attempts,phaseReached:Math.max(previous.phaseReached,metric.bossPhaseReached??0),dominantDamageSource:metric.dominantDamageSource||previous.dominantDamageSource,dodgeSuccess:clamp((previous.dodgeSuccess*(attempts-1)+(1-ratio(metric.damageTaken,metric.healthAtStart||120)))/attempts),campingRatio:clamp((previous.campingRatio*(attempts-1)+camping)/attempts),reinforcementUsage:clamp((previous.reinforcementUsage*(attempts-1)+(metric.reinforcementUsed?1:0))/attempts),lastDeathRoom:metric.room,telegraphMultiplier:clamp(1+attempts*.06,1,1.18),patternOrderOffset:attempts%3}}
export function migrateAdaptiveMemory(value:unknown,base:PlayerPerformanceProfile|null,samples:EncounterMetrics[]):AdaptiveMemory{if(!value||typeof value!=="object"||(value as {schemaVersion?:unknown}).schemaVersion!==1)return createAdaptiveMemory(base,samples);const raw=value as AdaptiveMemory,defaults=createAdaptiveMemory(base,samples);return{...defaults,...raw,player:{...defaults.player,...raw.player,confidence:{...defaults.player.confidence,...raw.player?.confidence}},habits:{...defaults.habits,...raw.habits,repeatedHabits:Array.isArray(raw.habits?.repeatedHabits)?raw.habits.repeatedHabits.slice(-8):[]},preferences:{...defaults.preferences,...raw.preferences},calibration:{...defaults.calibration,...raw.calibration,byTemplate:raw.calibration?.byTemplate||{}},pacingHistory:Array.isArray(raw.pacingHistory)?raw.pacingHistory.slice(-8):[],activeExperiment:raw.activeExperiment||null,boss:{...defaults.boss,...raw.boss}}}
