import{clamp,type AdaptiveTier}from"./adaptive";
/* eslint-disable @typescript-eslint/no-unused-vars -- seed is retained in the public deterministic planner signature */
import{getMapStyle,isKnownMapStyle}from"./customization";
import{applyRoomMapStyle,candidatePresetIds,getRoomPreset,getRoomTemplate,materializeRoom,type PreparedRoom,type RoomPlannerSelection}from"./rooms";

export type GameDirectorAction="set-difficulty-preference"|"adjust-enemy-density"|"adjust-enemy-speed"|"adjust-enemy-aggression"|"adjust-room-length"|"adjust-cover-density"|"adjust-hazard-frequency"|"adjust-pickup-frequency"|"select-map-style"|"request-recovery-room"|"request-pressure-room"|"request-boss-room"|"request-reinforcement-opportunity"|"adjust-adaptation-strength";
export interface GameDirectorActionDefinition{id:GameDirectorAction;description:string;kind:"number"|"string"|"boolean";minimum?:number;maximum?:number;allowedValues?:string[];appliesTo:"next-room"|"current-run"|"persistent-preference"}
const numeric=(id:GameDirectorAction,description:string,appliesTo:GameDirectorActionDefinition["appliesTo"]="current-run"):GameDirectorActionDefinition=>({id,description,kind:"number",minimum:-1,maximum:1,appliesTo});
export const GAME_DIRECTOR_ACTIONS:GameDirectorActionDefinition[]=[numeric("set-difficulty-preference","Shift challenge while preserving health and damage rules"),numeric("adjust-enemy-density","Use fewer or more enemies within room caps"),numeric("adjust-enemy-speed","Adjust movement speed within safe bounds"),numeric("adjust-enemy-aggression","Adjust attack pressure within safe bounds"),numeric("adjust-room-length","Prefer shorter or longer approved rooms"),numeric("adjust-cover-density","Prefer approved layouts with less or more cover"),numeric("adjust-hazard-frequency","Prefer fewer or more approved hazards"),numeric("adjust-pickup-frequency","Prefer fewer or more pickups"),{id:"select-map-style",description:"Select an unlocked map style",kind:"string",allowedValues:[],appliesTo:"persistent-preference"},{id:"request-recovery-room",description:"Prefer recovery pacing",kind:"boolean",appliesTo:"next-room"},{id:"request-pressure-room",description:"Prefer pressure pacing",kind:"boolean",appliesTo:"next-room"},{id:"request-boss-room",description:"Schedule a boss in 1 to 3 rooms",kind:"number",minimum:1,maximum:3,appliesTo:"current-run"},{id:"request-reinforcement-opportunity",description:"Surface an optional support opportunity",kind:"boolean",appliesTo:"next-room"},numeric("adjust-adaptation-strength","Adjust how strongly the Director responds","persistent-preference")];
export const GAME_DIRECTOR_ACTION_IDS=GAME_DIRECTOR_ACTIONS.map(x=>x.id);
const definitionById=new Map(GAME_DIRECTOR_ACTIONS.map(x=>[x.id,x]));

export type DirectorVoiceMode="off"|"menus"|"always";
export interface PlayerDirectorPreferences{schemaVersion:1;preferredDifficulty:number;enemyDensityPreference:number;enemySpeedPreference:number;enemyAggressionPreference:number;roomLengthPreference:number;coverDensityPreference:number;hazardPreference:number;pickupPreference:number;adaptationStrength:number;preferredMapStyleId:string|null;requestedNextRoomRole:"recovery"|"pressure"|null;requestedBossAfterRooms:number|null;reinforcementOpportunity:boolean;voiceMode:DirectorVoiceMode;voiceInputEnabled:boolean;language:"en";lastUpdatedAt:string}
export interface DirectorActionProposal{actionId:GameDirectorAction;value:number|string|boolean;reason:string}
export interface GameDirectorProposal{reply:string;interpretation:{intentSummary:string;scope:"next-room"|"current-run"|"persistent-preference"};proposedActions:DirectorActionProposal[];warnings:string[];requiresConfirmation:false;source:"local"|"openai"|"fallback"}
export interface DirectorHistoryEntry{id:string;request:string;reply:string;actions:DirectorActionProposal[];warnings:string[];source:GameDirectorProposal["source"];createdAt:string}

export const DEFAULT_DIRECTOR_PREFERENCES:PlayerDirectorPreferences={schemaVersion:1,preferredDifficulty:0,enemyDensityPreference:0,enemySpeedPreference:0,enemyAggressionPreference:0,roomLengthPreference:0,coverDensityPreference:0,hazardPreference:0,pickupPreference:0,adaptationStrength:0,preferredMapStyleId:null,requestedNextRoomRole:null,requestedBossAfterRooms:null,reinforcementOpportunity:false,voiceMode:"off",voiceInputEnabled:true,language:"en",lastUpdatedAt:new Date(0).toISOString()};
export function directorEnemyAdditionCount(intensity:number,activeEnemies:number,maximumEntities:number,roomIndex:number,roomState:string){if(intensity<=0||roomIndex<=5||roomState!=="fight")return 0;const space=Math.max(0,Math.trunc(maximumEntities)-Math.max(0,Math.trunc(activeEnemies))),requested=Math.max(1,Math.ceil(clamp(intensity,0,1)*5));return Math.min(space,requested);}
export function migrateDirectorPreferences(value:unknown):PlayerDirectorPreferences{const raw=value&&typeof value==="object"?value as Record<string,unknown>:{};const n=(key:string)=>clamp(Number(raw[key])||0,-1,1),style=typeof raw.preferredMapStyleId==="string"&&isKnownMapStyle(raw.preferredMapStyleId)?raw.preferredMapStyleId:null,role=raw.requestedNextRoomRole==="recovery"||raw.requestedNextRoomRole==="pressure"?raw.requestedNextRoomRole:null,boss=Number.isInteger(raw.requestedBossAfterRooms)?Math.max(1,Math.min(3,Number(raw.requestedBossAfterRooms))):null;return{schemaVersion:1,preferredDifficulty:n("preferredDifficulty"),enemyDensityPreference:n("enemyDensityPreference"),enemySpeedPreference:n("enemySpeedPreference"),enemyAggressionPreference:n("enemyAggressionPreference"),roomLengthPreference:n("roomLengthPreference"),coverDensityPreference:n("coverDensityPreference"),hazardPreference:n("hazardPreference"),pickupPreference:n("pickupPreference"),adaptationStrength:n("adaptationStrength"),preferredMapStyleId:style,requestedNextRoomRole:role,requestedBossAfterRooms:boss,reinforcementOpportunity:raw.reinforcementOpportunity===true,voiceMode:["off","menus","always"].includes(String(raw.voiceMode))?raw.voiceMode as DirectorVoiceMode:"off",voiceInputEnabled:raw.voiceInputEnabled!==false,language:"en",lastUpdatedAt:typeof raw.lastUpdatedAt==="string"?raw.lastUpdatedAt:new Date(0).toISOString()};}
export function migrateDirectorHistory(value:unknown):DirectorHistoryEntry[]{if(!Array.isArray(value))return[];return value.filter(x=>x&&typeof x==="object").slice(-12).map((x,i)=>{const r=x as Record<string,unknown>;return{id:typeof r.id==="string"?r.id:`legacy-${i}`,request:String(r.request||"").slice(0,400),reply:String(r.reply||"").slice(0,500),actions:Array.isArray(r.actions)?r.actions.slice(0,6) as DirectorActionProposal[]:[],warnings:Array.isArray(r.warnings)?r.warnings.filter(v=>typeof v==="string").slice(0,4) as string[]:[],source:["local","openai","fallback"].includes(String(r.source))?r.source as DirectorHistoryEntry["source"]:"local",createdAt:typeof r.createdAt==="string"?r.createdAt:new Date(0).toISOString()}})}

const unsafe=/(delete|files?|javascript|script|api\s*key|system\s*prompt|infinite\s*(health|damage)|disable\s*collision|download|execute|run\s+code|1000\s+enemies)/i;
const action=(actionId:GameDirectorAction,value:number|string|boolean,reason:string):DirectorActionProposal=>({actionId,value,reason});
export function chooseDefaultDirectorVariant(message:string,roomIndex:number):GameDirectorProposal{const variants:{name:string;actions:DirectorActionProposal[]}[]=[{name:"a tactical-cover variant",actions:[action("adjust-cover-density",.3,"Prefer an approved tactical layout with more cover"),action("adjust-room-length",-.1,"Keep the encounter focused")]},{name:"a controlled-pressure variant",actions:[action("request-pressure-room",true,"Use approved pressure pacing"),action("adjust-enemy-aggression",.15,"Add a small, bounded pressure increase")]},{name:"a mobile-skirmish variant",actions:[action("adjust-enemy-density",-.15,"Keep the battlefield readable"),action("adjust-enemy-speed",.2,"Emphasize movement over crowd size")]},{name:"a recovery-resource variant",actions:[action("request-recovery-room",true,"Use approved recovery pacing"),action("adjust-pickup-frequency",.25,"Provide a modest resource increase")]}],seed=`${message.trim().toLowerCase()}:${Math.max(0,Math.trunc(roomIndex))}`;let hash=2166136261;for(let i=0;i<seed.length;i++){hash^=seed.charCodeAt(i);hash=Math.imul(hash,16777619)}const chosen=variants[(hash>>>0)%variants.length];return{reply:`No specific gameplay preference was given, so I selected ${chosen.name}.`,interpretation:{intentSummary:"Director-selected approved room variant",scope:"next-room"},proposedActions:chosen.actions,warnings:[],requiresConfirmation:false,source:"fallback"};}
export function parseLocalDirectorRequest(message:string,unlockedMapStyleIds:string[]):GameDirectorProposal|null{const text=message.trim().slice(0,400),lower=text.toLowerCase();if(!text)return null;if(unsafe.test(text))return{reply:"I can adjust approved gameplay settings, but I cannot modify code, secrets, or unsafe engine rules. Try asking for a harder, calmer, or more tactical room.",interpretation:{intentSummary:"Unsafe engine request rejected",scope:"current-run"},proposedActions:[],warnings:["That request is outside safe gameplay controls."],requiresConfirmation:false,source:"local"};const actions:DirectorActionProposal[]=[];
 if(/easier|easy|less stress|calm|relax|chill|tone (it|things) down|lower (the )?difficulty/.test(lower))actions.push(action("set-difficulty-preference",-.35,"Reduce pressure safely"),action("request-recovery-room",true,"Use recovery pacing"));
 if(/harder|hard mode|challenge me|more difficult|tougher|intense|raise (the )?difficulty/.test(lower))actions.push(action("set-difficulty-preference",.35,"Increase tactical challenge"));
 if(/fewer (enemies|monsters|of them)|reduce (the )?(enemy|monster)|less crowded|smaller crowd/.test(lower))actions.push(action("adjust-enemy-density",-.35,"Reduce enemy density"));else if(/more (enemies|monsters)|add (some )?(enemies|monsters)|spawn (more )?(enemies|monsters)|enemy density|bigger (crowd|horde)|crowd me|swarm me/.test(lower))actions.push(action("adjust-enemy-density",.35,"Add enemies now when safe and increase future density within room caps"));
 if(/faster (enemies|monsters)|speed (the )?(enemies|monsters) up|quicker (enemies|monsters)/.test(lower))actions.push(action("adjust-enemy-speed",.3,"Increase enemy movement speed"));if(/slower (enemies|monsters)|slow (the )?(enemies|monsters) down/.test(lower))actions.push(action("adjust-enemy-speed",-.3,"Reduce enemy movement speed"));
 if(/more aggressive|high.pressure|attack more|relentless|rush me/.test(lower))actions.push(action("adjust-enemy-aggression",.3,"Increase attack pressure"));if(/less aggressive|attack less|give me breathing room|less pressure/.test(lower))actions.push(action("adjust-enemy-aggression",-.3,"Reduce attack pressure"));
 if(/more cover|tactical cover|more walls|tight layout|defensive layout/.test(lower))actions.push(action("adjust-cover-density",.4,"Prefer approved rooms with cover"));if(/less cover|open layout|open room|fewer walls|(?:open|clear) sightlines/.test(lower))actions.push(action("adjust-cover-density",-.35,"Prefer open layouts"));
 if(/longer (room|fight|level)|extended (room|fight)|make it longer/.test(lower))actions.push(action("adjust-room-length",.35,"Prefer a longer approved encounter"));if(/shorter (room|fight|level)|quick (room|fight)|make it shorter/.test(lower))actions.push(action("adjust-room-length",-.35,"Prefer a shorter approved encounter"));
 if(/more hazards|more traps|dangerous floor|environmental danger/.test(lower))actions.push(action("adjust-hazard-frequency",.4,"Increase approved environmental hazards"));if(/fewer hazards|less hazards|fewer traps|remove traps|safer floor/.test(lower))actions.push(action("adjust-hazard-frequency",-.4,"Reduce environmental hazards"));
 if(/more healing|more pickups|more resources|more loot|help me recover/.test(lower))actions.push(action("adjust-pickup-frequency",.5,"Prefer generous pickups"));if(/fewer pickups|reduce pickups|less healing|fewer resources|scarce resources/.test(lower))actions.push(action("adjust-pickup-frequency",-.4,"Prefer scarce pickups"));
 if(/adapt more|stronger adaptation|listen to me more|more responsive/.test(lower))actions.push(action("adjust-adaptation-strength",.45,"Respond more strongly to future preferences"));if(/adapt less|weaker adaptation|more stable|change less/.test(lower))actions.push(action("adjust-adaptation-strength",-.4,"Keep future adaptation more restrained"));
 if(/recovery room|rest room|breather|let me recover/.test(lower))actions.push(action("request-recovery-room",true,"Make the next room restorative"));if(/pressure room|high.pressure encounter|combat trial|test me/.test(lower))actions.push(action("request-pressure-room",true,"Make the next room focused pressure"));if(/reinforcement|support opportunity|backup|help option/.test(lower))actions.push(action("request-reinforcement-opportunity",true,"Surface optional support"));
 const boss=lower.match(/boss(?: fight| room)?(?:(?: after| in) (one|two|three|[1-3]) rooms?| next| now)?/);if(boss&&/boss/.test(lower)){const distance=boss[1]?({one:1,two:2,three:3}[boss[1] as "one"]||Number(boss[1])):1;actions.push(action("request-boss-room",distance,"Schedule an approved boss room"));}
 const style=unlockedMapStyleIds.find(id=>{const s=getMapStyle(id);return lower.includes(id)||lower.includes(s.name.toLowerCase())||(lower.includes("neon")&&id==="training-grid")||(lower.includes("brighter")&&["training-grid","frost-archive"].includes(id))});if(style)actions.push(action("select-map-style",style,"Use an unlocked visual style"));else if(/map style|neon|brighter|frost|ember/.test(lower))return{reply:"That style is not unlocked or available. I can keep Hollow Vault or use another unlocked style.",interpretation:{intentSummary:"Unavailable style",scope:"current-run"},proposedActions:[],warnings:["Only unlocked compatible styles can be used."],requiresConfirmation:false,source:"local"};
 if(!actions.length)return null;return{reply:"Applied. I kept the request inside safe room and balance limits.",interpretation:{intentSummary:text,scope:"current-run"},proposedActions:dedupeActions(actions).slice(0,6),warnings:[],requiresConfirmation:false,source:"local"};}
const dedupeActions=(actions:DirectorActionProposal[])=>[...new Map(actions.map(x=>[x.actionId,x])).values()];
export function sanitizeDirectorProposal(value:unknown,unlockedMapStyleIds:string[],source:GameDirectorProposal["source"]="openai"):GameDirectorProposal|null{if(!value||typeof value!=="object")return null;const raw=value as Record<string,unknown>,items=Array.isArray(raw.proposedActions)?raw.proposedActions:[];if(typeof raw.reply!=="string"||raw.reply.length>500||items.length>6)return null;const actions:DirectorActionProposal[]=[];const warnings:string[]=[];for(const item of items){if(!item||typeof item!=="object")return null;const o=item as Record<string,unknown>,id=o.actionId as GameDirectorAction,def=definitionById.get(id);if(!def||typeof o.reason!=="string")return null;let value=o.value;if(def.kind==="number"){if(typeof value!=="number"||!Number.isFinite(value))return null;const before=value;value=clamp(value,def.minimum!,def.maximum!);if(value!==before)warnings.push(`${id} was adjusted to its safe limit.`)}else if(def.kind==="boolean"&&typeof value!=="boolean")return null;else if(def.kind==="string"){if(typeof value!=="string"||id==="select-map-style"&&!unlockedMapStyleIds.includes(value))return null}actions.push(action(id,value as number|string|boolean,o.reason.slice(0,160)))}const interpretation=raw.interpretation as Record<string,unknown>;return{reply:raw.reply.slice(0,500),interpretation:{intentSummary:String(interpretation?.intentSummary||"Player preference").slice(0,200),scope:["next-room","current-run","persistent-preference"].includes(String(interpretation?.scope))?interpretation.scope as GameDirectorProposal["interpretation"]["scope"]:"current-run"},proposedActions:dedupeActions(actions),warnings:[...warnings,...(Array.isArray(raw.warnings)?raw.warnings.filter(x=>typeof x==="string").slice(0,4) as string[]:[])].slice(0,4),requiresConfirmation:false,source};}

export function applyDirectorProposal(current:PlayerDirectorPreferences,proposal:GameDirectorProposal):PlayerDirectorPreferences{const next={...current};for(const a of proposal.proposedActions){const v=typeof a.value==="number"?clamp(a.value,-1,1):a.value;if(a.actionId==="set-difficulty-preference")next.preferredDifficulty=v as number;if(a.actionId==="adjust-enemy-density")next.enemyDensityPreference=v as number;if(a.actionId==="adjust-enemy-speed")next.enemySpeedPreference=v as number;if(a.actionId==="adjust-enemy-aggression")next.enemyAggressionPreference=v as number;if(a.actionId==="adjust-room-length")next.roomLengthPreference=v as number;if(a.actionId==="adjust-cover-density")next.coverDensityPreference=v as number;if(a.actionId==="adjust-hazard-frequency")next.hazardPreference=v as number;if(a.actionId==="adjust-pickup-frequency")next.pickupPreference=v as number;if(a.actionId==="adjust-adaptation-strength")next.adaptationStrength=v as number;if(a.actionId==="select-map-style")next.preferredMapStyleId=a.value as string;if(a.actionId==="request-recovery-room")next.requestedNextRoomRole="recovery";if(a.actionId==="request-pressure-room")next.requestedNextRoomRole="pressure";if(a.actionId==="request-boss-room")next.requestedBossAfterRooms=Math.max(1,Math.min(3,Math.round(a.value as number)));if(a.actionId==="request-reinforcement-opportunity")next.reinforcementOpportunity=true}next.lastUpdatedAt=new Date().toISOString();return next;}

export function applyDirectorPreferencesToRoom(room:PreparedRoom,tier:AdaptiveTier,profileParameters:{profile:null;history:PreparedRoom[]},preferences:PlayerDirectorPreferences,unlockedMapStyleIds:string[],seed:string):PreparedRoom{const candidates=candidatePresetIds(room.roomSequenceIndex,tier,profileParameters.profile,profileParameters.history),wantedRole=preferences.requestedNextRoomRole;let best=room.presetId,bestScore=-Infinity;for(const id of candidates){const preset=getRoomPreset(id),template=preset&&getRoomTemplate(preset.templateId);if(!preset||!template)continue;const cover=clamp(template.obstacles.reduce((n,o)=>n+o.w*o.h,0)/(1132*572)/.16),length=clamp((template.estimatedDurationSeconds-40)/70),density=clamp(preset.difficultyScore/80),hazard=preset.hazardSetId==="none"?0:preset.hazardSetId==="slow_field"?.5:1,pickup=preset.pickupSetId==="generous"?1:preset.pickupSetId==="scarce"?0:.5;let score=-(Math.abs(density-(.5+preferences.enemyDensityPreference*.28))+Math.abs(length-(.5+preferences.roomLengthPreference*.3))+Math.abs(cover-(.5+preferences.coverDensityPreference*.35))+Math.abs(hazard-(.5+preferences.hazardPreference*.35))+Math.abs(pickup-(.5+preferences.pickupPreference*.4)));if(wantedRole&&preset.pacingRole===wantedRole)score+=2;if(score>bestScore){best=id;bestScore=score}}const base=getRoomPreset(best);if(!base)return room;const selection:RoomPlannerSelection={roomSequenceIndex:room.roomSequenceIndex,presetId:best,spawnPattern:preferences.coverDensityPreference<-.25?"spread":preferences.enemyDensityPreference>.25?"encircle":room.spawnPattern,countMultiplier:clamp(1+preferences.enemyDensityPreference*.2,.75,1.25),aggressionModifier:clamp(preferences.enemyAggressionPreference*.1,-.1,.1),reactionModifier:clamp(-preferences.enemySpeedPreference*.1,-.1,.1),predictedKillRate:room.predictedKillRate,predictedCompletionTimeSeconds:room.predictedCompletionTimeSeconds,predictedDamageTakenRatio:room.predictedDamageTakenRatio,adaptationReasonCodes:["player_director_request"],confidence:1,mapStyleId:preferences.preferredMapStyleId&&unlockedMapStyleIds.includes(preferences.preferredMapStyleId)?preferences.preferredMapStyleId:room.mapStyleId,pacingRole:wantedRole||base.pacingRole,behaviorProfileId:preferences.enemyAggressionPreference>.25?"aggressive":preferences.enemyAggressionPreference<-.25?"cautious":room.behaviorProfileId,roomModuleIds:room.roomModuleIds};let next=materializeRoom(room.roomSequenceIndex,best,tier,"local",selection);if(selection.mapStyleId&&unlockedMapStyleIds.includes(selection.mapStyleId))next=applyRoomMapStyle(next,{id:selection.mapStyleId,source:"selected",reasonCodes:["player_director_request"]});return{...next,adaptationReasonCodes:["player_director_request",...next.adaptationReasonCodes].slice(0,4)};}
