import{validatePreparedRoom,type PreparedRoom}from"./rooms";
import{createSuperState,savedSuperState,type SavedSuperState}from"./super";
export interface SavedPlayer{x:number;y:number;hp:number;maxHp:number;energy:number;maxEnergy:number;speed:number;inv:number;dashCd:number;dashMax:number;weapon:number;coins:number}
export interface ActiveRunSnapshot{schemaVersion:2;room:number;player:SavedPlayer;kills:number;currentRoom:PreparedRoom;preparedRooms:PreparedRoom[];roomHistory:PreparedRoom[];generationSeed:string;superState:SavedSuperState;savedAt:string}
const finite=(value:unknown)=>typeof value==="number"&&Number.isFinite(value);
export function sanitizeActiveRun(value:unknown):ActiveRunSnapshot|null{
 if(!value||typeof value!=="object")return null;const raw=value as Record<string,unknown>,player=raw.player as Record<string,unknown>,current=raw.currentRoom as PreparedRoom;if(![1,2].includes(Number(raw.schemaVersion))||!Number.isInteger(raw.room)||Number(raw.room)<1||!player||!validatePreparedRoom(current)||typeof raw.generationSeed!=="string"||raw.generationSeed.length<8)return null;const fields=["x","y","hp","maxHp","energy","maxEnergy","speed","inv","dashCd","dashMax","weapon","coins"] as const;if(fields.some(field=>!finite(player[field])))return null;const queue=Array.isArray(raw.preparedRooms)?raw.preparedRooms.filter((room):room is PreparedRoom=>validatePreparedRoom(room as PreparedRoom)).slice(0,4):[],history=Array.isArray(raw.roomHistory)?raw.roomHistory.filter((room):room is PreparedRoom=>validatePreparedRoom(room as PreparedRoom)).slice(-12):[];return{schemaVersion:2,room:Number(raw.room),player:Object.fromEntries(fields.map(field=>[field,Number(player[field])])) as unknown as SavedPlayer,kills:finite(raw.kills)?Math.max(0,Number(raw.kills)):0,currentRoom:current,preparedRooms:queue,roomHistory:history,generationSeed:raw.generationSeed,superState:savedSuperState(createSuperState(raw.superState as Partial<SavedSuperState>)),savedAt:typeof raw.savedAt==="string"?raw.savedAt:new Date(0).toISOString()};
}
export function createActiveRunSnapshot(input:Omit<ActiveRunSnapshot,"schemaVersion"|"savedAt"|"superState">&{superState?:SavedSuperState}):ActiveRunSnapshot{return{schemaVersion:2,...input,superState:savedSuperState(createSuperState(input.superState)),savedAt:new Date().toISOString()}}
