import {clamp,DIFFICULTY,type AdaptiveTier,type EncounterMetrics,type PlayerPerformanceProfile} from "./adaptive";
import {getMapStyle} from "./customization";
import {getEnemyGroup,getRoomTemplate,type PreparedRoom} from "./rooms";
import {reinforcementEfficiency,type ReinforcementDecision,type ReinforcementUsageSummary} from "./reinforcements";

export type PublicRoomSource="openai"|"local"|"fallback";
export interface RoomFactSnapshot{enemyCount:number;enemyComposition:string[];waveCount:number;waveDelaySeconds:number;coverDensity:"low"|"medium"|"high";hazardLevel:"none"|"low"|"high";healingAvailability:"generous"|"standard"|"scarce";eliteChance:number;flankRouteCount:number;enemyBehavior:string;roomModules:string[];pacingRole:string;enemyHealthModifier:number;enemyDamageModifier:number;mapStyleId:string;reinforcementBudget:number}
export interface PublicRoomChange{field:string;label:string;before:string;after:string;direction:"increase"|"decrease"|"changed"}
export interface NextRoomPreview{roomIndex:number;roomName:string;difficultyTier:AdaptiveTier;difficultyLabel:string;roomSource:PublicRoomSource;finalAppliedRoom:RoomFactSnapshot;changes:PublicRoomChange[];reasonCodes:string[];trend:"Small increase"|"Small decrease"|"Different approach"|"No mechanical change";prediction:{predictedCompletionTimeSeconds:number;predictedKillRate:number}}
export interface AIAdaptationRecord{id:string;createdAt:string;roomIndex:number;roomName:string;roomTemplateId:string;mapStyleId:string;mapStyleName:string;difficultyTier:AdaptiveTier;roomSource:PublicRoomSource;completionResult:"cleared"|"failed";observedMetrics:{accuracy:number;killRate:number;damageTakenRatio:number;completionTimeRatio:number;deaths:number;reinforcementUsageRate:number;superUsed:boolean;superTargetsHit:number};recommendation:{targetDifficultyScore:number;enemyCount:number;waveCount:number;mapStyleId:string;reinforcementBudget:number}|null;localAdjustments:{field:string;requestedValue:string;appliedValue:string;reasonCode:string}[];finalAppliedRoom:RoomFactSnapshot;changes:PublicRoomChange[];preservedRules:string[];reasonCodes:string[];prediction:{predictedCompletionTimeSeconds:number;actualCompletionTimeSeconds:number;predictedKillRate:number;actualKillRate:number};reinforcement:{decision:ReinforcementDecision|null;used:boolean;successful:boolean};nextRoom?:NextRoomPreview;}
export interface PublicSkillProfile{aim:number;movement:number;survival:number;tactics:number;reaction:number;resourceManagement:number;reinforcementEfficiency:number}
export interface PlayerFriendlyReason{title:string;explanation:string;icon:string;category:"performance"|"recovery"|"variety"|"support"|"visual"|"system"}

export const ADAPTATION_HISTORY_LIMIT=12;
export const PLAYER_FRIENDLY_REASONS:Record<string,PlayerFriendlyReason>={
 high_accuracy:{title:"Strong accuracy",explanation:"You landed more shots than expected in recent rooms.",icon:"◎",category:"performance"},
 low_damage_taken:{title:"Steady survival",explanation:"You avoided most incoming pressure in recent rooms.",icon:"◇",category:"performance"},
 fast_completion:{title:"Quick clears",explanation:"You completed recent rooms faster than expected.",icon:"➤",category:"performance"},
 repeated_deaths:{title:"Several difficult encounters",explanation:"The next room reduces pressure and creates more recovery space.",icon:"♥",category:"recovery"},
 low_ammo_efficiency:{title:"Heavy resource use",explanation:"The Director is keeping resource pressure readable while you rebuild reserves.",icon:"◆",category:"recovery"},
 strong_movement:{title:"Strong movement",explanation:"Your movement supports more routes and positioning choices.",icon:"↗",category:"performance"},
 weak_movement:{title:"Clearer routes",explanation:"The next room favors clearer paths and lower flank pressure.",icon:"↔",category:"recovery"},
 high_boredom_risk:{title:"More variety",explanation:"The next room changes its encounter pattern after several stable clears.",icon:"✦",category:"variety"},
 high_frustration_risk:{title:"High recent pressure",explanation:"The next room avoids combining too many demanding mechanics at once.",icon:"◇",category:"recovery"},
 room_repetition:{title:"A different chamber",explanation:"The room pattern changed to avoid repetition.",icon:"↻",category:"variety"},
 reinforcement_overuse:{title:"Frequent support use",explanation:"Recent support use slightly increased its energy cost or cooldown.",icon:"⌛",category:"support"},
 reinforcement_underuse:{title:"Support available",explanation:"A clear support option is available, but using it remains your choice.",icon:"+",category:"support"},
 boss_preparation:{title:"Warden preparation",explanation:"The next chamber prepares you for boss pressure.",icon:"!",category:"recovery"},
 recovery_required:{title:"Recovery window",explanation:"The next room preserves breathing room after recent pressure.",icon:"♥",category:"recovery"},
 local_fallback:{title:"Built-in Director",explanation:"The game selected a prepared room using its local adaptive system.",icon:"⌂",category:"system"},
 openai_fallback:{title:"Local adaptation active",explanation:"Online assistance was unavailable, so the game safely kept its prepared local room.",icon:"⌂",category:"system"},
 balanced_pressure:{title:"Balanced challenge",explanation:"The next room adds tactical variety without increasing enemy health.",icon:"≈",category:"performance"},
 aim_pressure:{title:"Accurate fire",explanation:"Your aim supports a modest increase in tactical pressure.",icon:"◎",category:"performance"},
 player_style_choice:{title:"Your selected style",explanation:"The room keeps your chosen visual theme.",icon:"✦",category:"visual"},
 avoid_style_repetition:{title:"Fresh visual theme",explanation:"The room theme changed to avoid repeating recent visuals.",icon:"↻",category:"visual"},
 style_rotation:{title:"Visual rotation",explanation:"The game selected another unlocked visual theme.",icon:"↻",category:"visual"},
 room_pacing_match:{title:"Theme matched to pacing",explanation:"The visual theme complements the next room's pace.",icon:"✦",category:"visual"},
 style_incompatible:{title:"Compatible theme used",explanation:"The selected theme did not fit this chamber, so the original vault theme was used.",icon:"◇",category:"visual"},
 openai_style_plan:{title:"AI-assisted theme",explanation:"OpenAI selected from your unlocked themes, and the game verified compatibility.",icon:"✦",category:"visual"},
 player_director_request:{title:"Your request",explanation:"This room reflects a safe gameplay preference you asked the Game Director to apply.",icon:"✦",category:"system"},
 crowd_control:{title:"More breathing room",explanation:"A slowing field can create space without defeating enemies for you.",icon:"◎",category:"support"},
 low_health:{title:"Low health",explanation:"Your current health entered the recovery range.",icon:"♥",category:"support"},
 sustained_damage:{title:"Sustained pressure",explanation:"Recent incoming damage prompted a defensive suggestion.",icon:"◇",category:"support"},
 low_survival:{title:"Protection suggested",explanation:"Your recent survival trend favors temporary protection.",icon:"◇",category:"support"},
 high_enemy_pressure:{title:"Several nearby threats",explanation:"Active enemies are limiting your movement space.",icon:"!",category:"support"},
 weak_aim:{title:"Clearer shots",explanation:"A slowing field can create more readable shots.",icon:"◎",category:"support"},
 balanced_support:{title:"Optional protection",explanation:"A defensive option is available without changing room balance.",icon:"◇",category:"support"},
 profile_targeted:{title:"Matched to your play",explanation:"The room uses separate aim, movement, survival, and tactical estimates instead of only one difficulty score.",icon:"◎",category:"performance"},
 low_confidence_neutral:{title:"Still gathering evidence",explanation:"Confidence is still low, so the Director kept this room close to neutral.",icon:"◇",category:"system"},
 pacing_recovery:{title:"Recovery pacing",explanation:"Recent pressure triggered a readable recovery room before difficulty rises again.",icon:"♥",category:"recovery"},
 pacing_pressure:{title:"Pressure pacing",explanation:"Several stable results support a focused tactical challenge.",icon:"!",category:"performance"},
 pacing_experiment:{title:"New encounter style",explanation:"The director is testing one safe encounter variable while core combat values stay unchanged.",icon:"◇",category:"performance"},
 behavior_coordinated:{title:"Coordinated enemies",explanation:"Enemy movement favors teamwork and positioning without increasing health or damage.",icon:"↗",category:"variety"},
 behavior_flanking:{title:"Positioning test",explanation:"A bounded flanking profile adds route pressure while preserving telegraphs and spawn safety.",icon:"↔",category:"variety"},
 behavior_area_control:{title:"Movement opportunity",explanation:"Readable area pressure encourages repositioning after repeated stationary combat evidence.",icon:"◎",category:"variety"},
};
export const UNKNOWN_FRIENDLY_REASON:PlayerFriendlyReason={title:"Recent room results",explanation:"The Director made a small, verified adjustment using your recent rooms.",icon:"◇",category:"system"};
export const friendlyReason=(code:string)=>PLAYER_FRIENDLY_REASONS[code]||UNKNOWN_FRIENDLY_REASON;
export const ADAPTATION_REASON_TEXT:Record<string,string>=Object.fromEntries(Object.entries(PLAYER_FRIENDLY_REASONS).map(([code,value])=>[code,value.explanation]));
export const adaptationReasonText=(code:string)=>friendlyReason(code).explanation;
export const difficultyLabel=(tier:AdaptiveTier)=>({assisted:"Recovery",relaxed:"Relaxed",standard:"Balanced",challenging:"Challenging",expert:"Intense"})[tier];
export const skillLabel=(value:number)=>value<.35?"Developing":value<.62?"Balanced":value<.82?"Strong":"Excellent";

export function roomFacts(plan:PreparedRoom,tier:AdaptiveTier,reinforcementBudget=0,actualEnemyCount?:number):RoomFactSnapshot{
 const template=getRoomTemplate(plan.templateId);const params=DIFFICULTY[tier];let estimated=0;const composition=new Set<string>();for(const wave of plan.waves)for(const placement of wave.groups){const group=getEnemyGroup(placement.enemyGroupId);if(!group)continue;group.kinds.forEach(kind=>composition.add(kind));estimated+=group.kinds.includes("boss")?1:Math.min(group.maximumPerRoom,Math.max(1,Math.round(group.baseCount*placement.countMultiplier*params.enemyCountMultiplier)))}
 const coverRatio=(template?.obstacles.reduce((sum,o)=>sum+o.w*o.h,0)||0)/(1132*572),coverDensity=coverRatio>.12?"high":coverRatio>.055?"medium":"low";const waveDelay=plan.waves.slice(1).reduce((n,w)=>n+w.delaySeconds,0);
 return{enemyCount:Number.isFinite(actualEnemyCount)?Math.max(0,actualEnemyCount!):estimated,enemyComposition:[...composition],waveCount:plan.waves.length,waveDelaySeconds:waveDelay,coverDensity,hazardLevel:plan.hazardSetId==="none"?"none":plan.hazardSetId==="slow_field"?"low":"high",healingAvailability:plan.pickupSetId,eliteChance:clamp(params.eliteSpawnChance+(plan.pacingRole==="elite"?.08:0)),flankRouteCount:plan.spawnPattern==="encircle"?2:plan.spawnPattern==="flank"?1:0,enemyBehavior:plan.behaviorProfileId||"balanced",roomModules:plan.roomModuleIds||[],pacingRole:plan.pacingRole,enemyHealthModifier:1,enemyDamageModifier:1,mapStyleId:plan.mapStyleId,reinforcementBudget};
}

const value=(field:keyof RoomFactSnapshot,v:RoomFactSnapshot[typeof field])=>field==="eliteChance"?`${Math.round(Number(v)*100)}%`:field==="waveDelaySeconds"?`${Number(v).toFixed(1)}s`:field==="mapStyleId"?getMapStyle(String(v)).name:Array.isArray(v)?v.join(", "):String(v);
export function compareRoomFacts(previous:RoomFactSnapshot|null,current:RoomFactSnapshot):PublicRoomChange[]{if(!previous)return[];const fields:[keyof RoomFactSnapshot,string][]=[["enemyCount","Enemy count"],["enemyComposition","Enemy composition"],["waveCount","Wave count"],["waveDelaySeconds","Wave delay"],["coverDensity","Cover density"],["hazardLevel","Hazard level"],["healingAvailability","Healing availability"],["eliteChance","Elite chance"],["flankRouteCount","Flanking routes"],["enemyBehavior","Enemy behavior"],["roomModules","Room modules"],["pacingRole","Pacing role"],["mapStyleId","Map style"],["reinforcementBudget","Reinforcement budget"]];return fields.flatMap(([field,label])=>{const before=value(field,previous[field]),after=value(field,current[field]);if(before===after)return[];const a=typeof current[field]==="number"?Number(current[field]):NaN,b=typeof previous[field]==="number"?Number(previous[field]):NaN;return[{field,label,before,after,direction:Number.isFinite(a)&&Number.isFinite(b)?a>b?"increase":"decrease":"changed"}]})}

export function buildAdaptationRecord(input:{plan:PreparedRoom;previousPlan:PreparedRoom|null;tier:AdaptiveTier;metrics:EncounterMetrics;previousMetrics?:EncounterMetrics;reinforcementDecision:ReinforcementDecision|null;reinforcementUsed:boolean;reinforcementSuccessful:boolean;usage:ReinforcementUsageSummary;sourceOverride?:PublicRoomSource}):AIAdaptationRecord{
 const m=input.metrics,actualKillRate=clamp(m.kills/Math.max(1,m.enemiesSpawned||m.kills)),facts=roomFacts(input.plan,input.tier,input.reinforcementDecision?.resourceCost||0,m.enemiesSpawned),previousFacts=input.previousPlan?roomFacts(input.previousPlan,input.tier,0,input.previousMetrics?.enemiesSpawned):null,recommendation=input.plan.plannerRecommendation?{targetDifficultyScore:input.plan.targetDifficultyScore,enemyCount:roomFacts(input.plan,input.tier).enemyCount,waveCount:input.plan.waves.length,mapStyleId:input.plan.plannerRecommendation.mapStyleId,reinforcementBudget:input.reinforcementDecision?.resourceCost||0}:null;const localAdjustments=[] as AIAdaptationRecord["localAdjustments"];
 if(input.plan.plannerRecommendation&&input.plan.plannerRecommendation.mapStyleId!==input.plan.mapStyleId)localAdjustments.push({field:"mapStyleId",requestedValue:input.plan.plannerRecommendation.mapStyleId,appliedValue:input.plan.mapStyleId,reasonCode:"style_incompatible"});
 const source=input.sourceOverride||(input.plan.source==="gpt"?"openai":input.plan.source==="fallback"?"fallback":"local"),reasonCodes=[...new Set([...input.plan.adaptationReasonCodes,...input.plan.styleReasonCodes,...(input.reinforcementDecision?.reasonCodes||[])])].slice(0,8);
 return{id:`room-${input.plan.roomSequenceIndex}-${Math.round(m.durationMs)}`,createdAt:new Date().toISOString(),roomIndex:input.plan.roomSequenceIndex,roomName:getRoomTemplate(input.plan.templateId)?.name||"Unknown Chamber",roomTemplateId:input.plan.templateId,mapStyleId:input.plan.mapStyleId,mapStyleName:getMapStyle(input.plan.mapStyleId).name,difficultyTier:input.tier,roomSource:source,completionResult:m.completed?"cleared":"failed",observedMetrics:{accuracy:clamp(m.shotsHit/Math.max(1,m.shotsFired)),killRate:actualKillRate,damageTakenRatio:clamp(m.damageTaken/Math.max(1,m.healthAtStart||120),0,2),completionTimeRatio:clamp(m.durationMs/Math.max(1,m.expectedCompletionTimeMs||90000),0,2),deaths:m.deaths,reinforcementUsageRate:clamp(input.usage.recentUses/3),superUsed:(m.supersActivated||0)>0,superTargetsHit:m.superTargetsHit||0},recommendation,localAdjustments,finalAppliedRoom:facts,changes:compareRoomFacts(previousFacts,facts),preservedRules:["Enemy health adaptation unchanged","Enemy damage adaptation unchanged","Collision geometry unchanged","Spawn-rate configuration unchanged"],reasonCodes,prediction:{predictedCompletionTimeSeconds:input.plan.predictedCompletionTimeSeconds,actualCompletionTimeSeconds:m.durationMs/1000,predictedKillRate:input.plan.predictedKillRate,actualKillRate},reinforcement:{decision:input.reinforcementDecision,used:input.reinforcementUsed,successful:input.reinforcementSuccessful}};
}
export const appendAdaptationRecord=(records:AIAdaptationRecord[],record:AIAdaptationRecord)=>[...records,record].slice(-ADAPTATION_HISTORY_LIMIT);
export function publicSkillProfile(profile:PlayerPerformanceProfile|null,usage:ReinforcementUsageSummary):PublicSkillProfile{return{aim:profile?.dimensions.aim??0,movement:profile?.dimensions.movement??0,survival:profile?.dimensions.survival??0,tactics:profile?.dimensions.tactical??0,reaction:profile?.dimensions.reaction??0,resourceManagement:profile?.dimensions.resource??0,reinforcementEfficiency:reinforcementEfficiency(usage)}}
export function difficultyTrend(records:AIAdaptationRecord[]):"Stable"|"Slight Increase"|"Slight Decrease"{if(records.length<2)return"Stable";const a=records.at(-2)!.finalAppliedRoom,b=records.at(-1)!.finalAppliedRoom;const score=(x:RoomFactSnapshot)=>x.enemyCount+x.waveCount*2+x.eliteChance*10+x.flankRouteCount*1.5+(x.hazardLevel==="high"?3:x.hazardLevel==="low"?1:0);const delta=score(b)-score(a);return delta>1?"Slight Increase":delta< -1?"Slight Decrease":"Stable"}

const roomPressureScore=(facts:RoomFactSnapshot)=>facts.enemyCount+facts.waveCount*2+facts.eliteChance*10+facts.flankRouteCount*1.5+(facts.hazardLevel==="high"?3:facts.hazardLevel==="low"?1:0)+(facts.healingAvailability==="scarce"?2:facts.healingAvailability==="generous"?-2:0);
export function buildNextRoomPreview(previousPlan:PreparedRoom,nextPlan:PreparedRoom,previousTier:AdaptiveTier,nextTier:AdaptiveTier):NextRoomPreview{
 const previousFacts=roomFacts(previousPlan,previousTier),nextFacts=roomFacts(nextPlan,nextTier),changes=compareRoomFacts(previousFacts,nextFacts),delta=roomPressureScore(nextFacts)-roomPressureScore(previousFacts),mechanicalChanges=changes.filter(change=>change.field!=="mapStyleId");
 const trend:NextRoomPreview["trend"]=delta>1?"Small increase":delta< -1?"Small decrease":mechanicalChanges.length?"Different approach":"No mechanical change";
 return{roomIndex:nextPlan.roomSequenceIndex,roomName:getRoomTemplate(nextPlan.templateId)?.name||"Unknown Chamber",difficultyTier:nextTier,difficultyLabel:difficultyLabel(nextTier),roomSource:nextPlan.source==="gpt"?"openai":nextPlan.source==="fallback"?"fallback":"local",finalAppliedRoom:nextFacts,changes,reasonCodes:[...new Set([...nextPlan.adaptationReasonCodes,...nextPlan.styleReasonCodes])].slice(0,8),trend,prediction:{predictedCompletionTimeSeconds:nextPlan.predictedCompletionTimeSeconds,predictedKillRate:nextPlan.predictedKillRate}};
}
export function attachNextRoomPreview(record:AIAdaptationRecord,previousPlan:PreparedRoom,nextPlan:PreparedRoom,previousTier:AdaptiveTier,nextTier:AdaptiveTier):AIAdaptationRecord{return{...record,nextRoom:buildNextRoomPreview(previousPlan,nextPlan,previousTier,nextTier)}}
export function replaceLatestRecord(records:AIAdaptationRecord[],record:AIAdaptationRecord):AIAdaptationRecord[]{const index=records.findIndex(item=>item.id===record.id);if(index<0)return appendAdaptationRecord(records,record);return records.map(item=>item.id===record.id?record:item).slice(-ADAPTATION_HISTORY_LIMIT)}
export function playerObservations(record:AIAdaptationRecord|null):{icon:string;text:string}[]{if(!record)return[];const m=record.observedMetrics,observations=[] as {icon:string;text:string}[];if(m.accuracy>=.7)observations.push({icon:"◎",text:"Your accuracy was strong."});else if(m.accuracy<.35)observations.push({icon:"◎",text:"Your recent shots needed more setup time."});if(m.completionTimeRatio<=.85)observations.push({icon:"➤",text:"You cleared the room faster than expected."});else if(m.completionTimeRatio>=1.25)observations.push({icon:"⌛",text:"The room took longer than its recent target."});if(m.damageTakenRatio<=.2)observations.push({icon:"◇",text:"You avoided most incoming damage."});else if(m.damageTakenRatio>=.55)observations.push({icon:"♥",text:"You took sustained damage during the room."});if(m.superUsed)observations.push({icon:"✦",text:`Your Energy Nova struck ${m.superTargetsHit} ${m.superTargetsHit===1?"target":"targets"}.`});if(record.reinforcement.used)observations.push({icon:"+",text:record.reinforcement.successful?"Your reinforcement helped during the encounter.":"You tried a reinforcement during the encounter."});return observations.slice(0,3)}
export function roomSourceCopy(source:PublicRoomSource){return source==="openai"?{title:"AI assisted",text:"OpenAI suggested the room plan. The game checked it before applying it."}:source==="fallback"?{title:"Local adaptation active",text:"Online assistance was unavailable, so the game used a prepared room with your current settings."}:{title:"Local system",text:"The room was selected by the game's built-in adaptive Director."}}
export function directorStatusCopy(input:{enabled:boolean;records:AIAdaptationRecord[];plannerStatus:string}){if(!input.enabled)return{title:"Adaptive mode is off",text:"Rooms use your selected fixed difficulty."};if(!input.records.length)return{title:"The AI Director is still learning",text:"Complete the introductory rooms to see how the game adapts."};if(input.plannerStatus==="planning")return{title:"The next room is ready",text:"Later rooms are being prepared in the background."};const latest=input.records.at(-1);if(latest?.nextRoom?.roomSource==="fallback")return{title:"Local adaptation active",text:"The game is continuing with its built-in adaptive system."};return{title:"AI Director active",text:"Future rooms are adapting to your recent gameplay."}}
export function changeCategory(field:string):"Enemies"|"Room"|"Resources"|"Reinforcements"{if(["enemyCount","enemyComposition","eliteChance"].includes(field))return"Enemies";if(["healingAvailability"].includes(field))return"Resources";if(field==="reinforcementBudget")return"Reinforcements";return"Room"}
export const dashboardSections=(detail:"simple"|"detailed")=>detail==="simple"?["status","observations","changes","reason","nextDifficulty","source","reinforcement"]:["status","observations","changes","reason","nextDifficulty","source","reinforcement","metrics","prediction","localAdjustments","history"];
