import {NextRequest,NextResponse} from "next/server";
import {requestReinforcementRecommendation} from "@/lib/server/adaptive-reinforcements/planner";
import {allowedReinforcementIdsKnown,reinforcementRequestSchema} from "@/lib/server/adaptive-reinforcements/schemas";
import {adaptiveReinforcementsEnabled,adaptiveRoomsModel,adaptiveRoomsTimeoutMs,boundedInteger,getOpenAIClient} from "@/lib/server/openai/client";

export const runtime="nodejs";export const maxDuration=10;
const calls=new Map<string,{count:number;resetAt:number;lastCallAt:number}>(),cache=new Map<string,{expiresAt:number;value:unknown}>();
const failure=(error:string,status:number)=>NextResponse.json({success:false,error,fallbackRequired:true},{status});
export async function POST(request:NextRequest){const declared=Number(request.headers.get("content-length")||0);if(declared>6000)return failure("payload_too_large",413);let text:string;try{text=await request.text()}catch{return failure("invalid_request",400)}if(Buffer.byteLength(text,"utf8")>6000)return failure("payload_too_large",413);let raw:unknown;try{raw=JSON.parse(text)}catch{return failure("invalid_json",400)}const parsed=reinforcementRequestSchema.safeParse(raw);if(!parsed.success)return failure("invalid_request",400);const body=parsed.data;if(!allowedReinforcementIdsKnown(body))return failure("invalid_candidates",400);if(!adaptiveReinforcementsEnabled())return failure("adaptive_reinforcements_disabled",503);
 const now=Date.now(),cacheKey=JSON.stringify([body.playerProfile,body.currentRoom,body.recentUsage,body.allowedReinforcementTypeIds]),cached=cache.get(cacheKey);if(cached&&cached.expiresAt>now)return NextResponse.json({success:true,source:"cache",recommendation:cached.value,cached:true});const address=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||request.headers.get("cf-connecting-ip")||"local",key=`${address.slice(0,80)}:${body.sessionId}`,prior=calls.get(key),limit=boundedInteger(process.env.ADAPTIVE_REINFORCEMENTS_MAX_CALLS_PER_SESSION,3,1,8),cooldown=boundedInteger(process.env.ADAPTIVE_REINFORCEMENTS_COOLDOWN_MS,15000,0,120000);if(prior&&prior.resetAt>now&&(prior.count>=limit||now-prior.lastCallAt<cooldown))return failure(prior.count>=limit?"rate_limited":"cooldown_active",429);const openai=getOpenAIClient();if(!openai)return failure("openai_not_configured",503);calls.set(key,{count:prior&&prior.resetAt>now?prior.count+1:1,resetAt:prior&&prior.resetAt>now?prior.resetAt:now+86400000,lastCallAt:now});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),adaptiveRoomsTimeoutMs());try{const recommendation=await requestReinforcementRecommendation(openai,adaptiveRoomsModel(),body,controller.signal);if(!recommendation)return failure("invalid_provider_response",503);cache.set(cacheKey,{expiresAt:now+3600000,value:recommendation});return NextResponse.json({success:true,source:"openai",recommendation,cached:false})}catch{return failure("provider_unavailable",503)}finally{clearTimeout(timer)}}
